name: ci-demo-lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - feature/*
      - hotfix/*
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4   # clone the repository
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.21' 
      
      - run: | 
          python --version
          python -m pip --upgrade pip
          pip --version
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Lint code
        run: flake8 example.py
    # steps:
    #   - name: Checkout code
    #     # `uses` is used for reusing an action of the GitHub Actions
    #     uses: actions/checkout@v4   # clone the repository
      
    #   - name: Setup Python
    #     uses: actions/setup-python@v5
    #     with:
    #       python-version: '3.9.21' 
    #   # - run: python my_script.py  # Run a Python script
        
    #     # | is a multiline string in YAML (so it will exec multiple commands)
    #   - run: | 
    #       python --version
    #       python -m pip --upgrade pip
    #       pip --version
      
    #   - name: Install dependencies
    #     run: pip install -r requirements.txt
      
    #   - name: Lint code
    #     run: flake8 example.py