name: ci-demo-lint

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
      - feature/*
      - hotfix/*
jobs:
  lint:
    # runs-on: ubuntu-latest

    # we can try to run the job on different operating systems
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.9', '3.10', '3.13']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4   # clone the repository
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          # python-version: '3.9.21'
          python-version: ${{matrix.python-version}} 
      
      - run: | 
          python --version
          python -m pip install --upgrade pip
          pip --version
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Lint code
        run: flake8 example.py
  unit-test:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9.21'
    
    - name: Run Unit tests
      run: python -m unittest discover
       